version: "3.8"
services:
  prometheus:
    image: quay.io/prometheus/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  prometheus_data: {}
